apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  namespace: odoo
  labels:
    app: odoo-shop
spec:
  ports:
    - port: 8069
      protocol: TCP
  selector:
    app: odoo-shop
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  namespace: odoo
  labels:
    app: odoo-shop
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-shop
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: frontend
    spec:
      containers:
        - image: odoo:latest
          name: odoo
          env:
          - name: HOST
            value: odoo-db
          - name: USER
            value: odoo
          - name: PASSWORD
            value: password
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo-shop
          volumeMounts:
          - name: odoo-pvc
            mountPath: /var/lib/odoo
      volumes:
      - name: odoo-pvc
        persistentVolumeClaim:
          claimName: odoo-pvc
---